name: "Nmap Action"
description: "Runs nmap on a target host"
author: gipo355
inputs:
  host:
    description: "Host to scan"
    required: false
    default: "localhost"
  generate-report:
    description: "Generate a report"
    required: false
    default: "false"
  upload-report-to-code-scans:
    description: "Upload the report"
    required: false
    default: "false"
  nmap-arguments:
    description: "Arguments to pass to nmap"
    required: false
    default: "-sV"
  run-vulners:
    description: "Use vulners script"
    required: false
    default: "false"
outputs:
  time: # id of output
    description: "The time we greeted you"
  arg:
    description: "The argument we passed"
runs:
  using: "docker"
  # in repo
  # image: "Dockerfile"
  # in registry.
  # image: "Dockerfile"
  # image: "docker://docker.io/halamert/vuln-tests-action"
  image: "docker://gipo355/nmap-go-wrapper:latest"
  # image: "docker://vuln-tests-action"
  args:
    - ${{ inputs.who-to-greet }}
    - --host ${{ inputs.host }}
