name: "Nmap Action"
description: "Runs nmap on a target host"
author: gipo355
inputs:
  target:
    description: "Host to scan"
    required: false
    default: "localhost"
  generate-report:
    description: "Generate a report"
    required: false
    default: "false"
  generate-sarif:
    description: "Generate a SARIF report"
    required: false
    default: "false"
  # must be done separately
  # upload-report-to-code-scans:
  #   description: "Upload the report"
  #   required: false
  #   default: "false"
  nmap-arguments:
    description: "Arguments to pass to nmap"
    required: false
    default: "-sP"
  run-vulners:
    description: "Use vulners script"
    required: false
    default: "false"
  run-vulscan:
    description: "Use vulscan script"
    required: false
    default: "false"
runs:
  using: "docker"
  image: "docker://gipo355/nmap-go-wrapper:latest"
  args:
    - ${{ inputs.who-to-greet }}
    - "--host ${{ inputs.host }}"
