name: "Vuln Scanners Nmap Action"
description: "Runs nmap on a target host"
author: gipo355
inputs:
  target:
    description: "Host to scan"
    required: true
    default: "localhost"
  port:
    description: "Port to scan"
    required: true
    default: ""
  generate-reports:
    description: "Generate a report"
    required: false
    default: "true"
  generate-sarif:
    description: "Generate a SARIF report"
    required: false
    default: "true"
  reports-dir:
    description: "Directory to store the reports"
    required: false
    default: "nmap-reports"
  # must be done separately
  # upload-report-to-code-scans:
  #   description: "Upload the report"
  #   required: false
  #   default: "false"
  nmap-arguments:
    description: "Arguments to pass to nmap for the direct scan"
    required: false
    default: "-sP"
  vulners:
    description: "Use vulners scripts"
    required: false
    default: "false"
  vulscan:
    description: "Use vulscan scripts"
    required: false
    default: "false"
runs:
  using: "docker"
  image: "docker://gipo355/vuln-docker-scanners:latest"
  args:
    - "nmap"
    - "--target=${{ inputs.host }}"
    - "--port=${{ inputs.port }}"
    - "--generate-reports=${{ inputs.generate-reports }}"
    - "--generate-sarif=${{ inputs.generate-sarif }}"
    - "--nmap-arguments=${{ inputs.nmap-arguments }}"
    - "--vulners=${{ inputs.vulners }}"
    - "--vulscan=${{ inputs.vulscan }}"
    - "--reports-dir=${{ inputs.reports-dir }}"
